#**Nive Bayes**

This is propability based lrarning model.

this uses bayes theorem, everything based on the event and evidence for the event

            P(A)*p(B/A)
    P(A/B)= -----------
               P(B)

P(A/B) - posterior propability

P(B/A) - likelihood propability

P(A) - prior property

P(B) - marginal propability

---

**Example question:**

Find the propability for play golf if outlook is sunny.

<img src="https://res.cloudinary.com/dlbuareax/image/upload/v1779888349/naive_bayes_data_rb2i1w.png" width=400/>

**Process**
 1. constructing a frequency table for each attribute against the target.
 2. Then, transforming the frequency tables to likelihood tables.
 3. finally use the Naive Bayesian equation to calculate the posterior probability for each class.
 4. The class with the highest posterior probability is the outcome of prediction.

**Solution**

<img src="https://res.cloudinary.com/dlbuareax/image/upload/v1779888363/Bayes_3_igsqna.png" width=400/>

**Types of naive bayes**

<img src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*AcJwvINWo0ctS9AeYAldCQ.png" width=500/>

**Remaind the formula**

<img src="https://res.cloudinary.com/dlbuareax/image/upload/v1779888356/Bayes_rule_rh3wtt.png" width=400/>

#**Steps i follow**


1. Perform EDA
2. spliting dataset
3. Encoding the data, since there is no Null values.
4. Remoing outlier
5. Scale tha data
6. Select the Top 5 important feature
7. Decompose the features
8. Balance the class
9. Model Training
10. Evaluation

In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/drive/MyDrive/AI Training/Datasets/Copy of Churn_Modelling.csv')

In [4]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [7]:
x=df[['CreditScore', 'Geography', 'Gender', 'Age',	'Tenure',	'Balance',	'NumOfProducts',	'HasCrCard',	'IsActiveMember',	'EstimatedSalary'	]]
y=df['Exited']

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=42)

In [9]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
for i in x_train[['Geography', 'Gender']]:
  x_train[i]=le.fit_transform(x_train[i])
  x_test[i]=le.transform(x_test[i])

In [10]:
x_test.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
6252,596,1,1,32,3,96709.07,2,0,0,41788.37
4684,623,0,1,43,1,0.00,2,1,1,146379.30
1731,601,2,0,44,4,0.00,2,1,0,58561.31
4742,506,1,1,59,8,119152.10,2,1,1,170679.74
4521,560,2,0,27,7,124995.98,1,1,1,114669.79

In [11]:
x_train.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
9254,686,0,1,32,6,0.00,2,1,1,179093.26
1561,632,1,1,42,4,119624.60,2,1,1,195978.86
1670,559,2,1,24,3,114739.92,1,1,0,85891.02
6087,561,0,0,27,9,135637.00,1,1,0,153080.40
6669,517,0,1,56,9,142147.32,1,0,0,39488.04

In [12]:
def remove_outlier(x_train, x_test):
  !pip install feature-engine
  from feature_engine.outliers import Winsorizer
  winsor = Winsorizer(
    capping_method="quantiles",
    tail="both",
    fold=0.01
)

  for col in x_train.columns.to_list():

    x_train[col] = winsor.fit_transform(x_train[[col]])
    x_test[col] = winsor.transform(x_test[[col]])

  return (x_train, x_test)

In [13]:
x_train, x_test=remove_outlier(x_train, x_test)

Collecting feature-engine
  Downloading feature_engine-1.9.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.18.2 in /usr/local/lib/python3.12/dist-packages (from feature-engine) (2.0.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from feature-engine) (2.2.2)
Requirement already satisfied: scikit-learn>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from feature-engine) (1.6.1)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from feature-engine) (1.16.3)
Requirement already satisfied: statsmodels>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from feature-engine) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->feature-engine) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->feature-engine) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->feature-engine) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.0->feature-engine) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.0->feature-engine) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.11.1->feature-engine) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.11.1->feature-engine) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->feature-engine) (1.17.0)
Downloading feature_engine-1.9.4-py3-none-any.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.5/243.5 kB 5.6 MB/s eta 0:00:00
Installing collected packages: feature-engine
Successfully installed feature-engine-1.9.4

In [14]:
def scale_data(x_train, x_test):
  from sklearn.preprocessing import StandardScaler
  ss=StandardScaler()
  for i in x_train.columns.to_list():
    x_train[i]=ss.fit_transform(x_train[[i]])
    x_test[i]=ss.transform(x_test[[i]])

  return(x_train, x_test)

In [15]:
x_train, x_test=scale_data(x_train, x_test)

In [16]:
def feature_select(x_train, y_train):
  from sklearn.feature_selection import SelectKBest
  from sklearn.feature_selection import mutual_info_classif

  selector = SelectKBest(
      score_func=mutual_info_classif,
      k=5
  )

  x_train_new = selector.fit_transform(
      x_train,
      y_train
  )

  selected_features = x_train.columns[
      selector.get_support()
  ]

  return selected_features

In [17]:
print(feature_select(x_train, y_train))

Index(['Geography', 'Gender', 'Age', 'Balance', 'NumOfProducts'], dtype='object')

In [18]:
def decompose(x_train, x_test):
  from sklearn.decomposition import PCA
  pca=PCA(n_components=2)
  x_train=pca.fit_transform(x_train)
  x_test=pca.transform(x_test)

  return (x_train, x_test)

In [19]:
x_train=x_train[['Geography', 'Age', 'Balance', 'NumOfProducts', 'IsActiveMember']]
x_test=x_test[['Geography', 'Age', 'Balance', 'NumOfProducts', 'IsActiveMember']]

In [20]:
x_train, x_test=decompose(x_train, x_test)

In [21]:
x_train.shape

(8000, 2)

In [22]:
y_train.shape

(8000,)

In [23]:
def clear_imbalance(x_train, y_train):
  from imblearn.over_sampling import RandomOverSampler
  os=RandomOverSampler()

  x_train_sampled, y_train_sampled = os.fit_resample(x_train, y_train)

  return (x_train_sampled, y_train_sampled)

In [24]:
x_train, y_train=clear_imbalance(x_train, y_train)

In [25]:
from sklearn.naive_bayes import BernoulliNB

In [26]:
model=BernoulliNB(binarize=None)
model.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/naive_bayes.py:1209: RuntimeWarning: invalid value encountered in log
  self.feature_log_prob_ = np.log(smoothed_fc) - np.log(

BernoulliNB(binarize=None)

In [27]:
y_pred=model.predict(x_test)

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

print('accuracy_score')
a=accuracy_score(y_test, y_pred)
print(a)
'printconfusion_matrix'
print(confusion_matrix(y_test, y_pred))
print()
print('classification_report')
print(classification_report(y_test, y_pred))

accuracy_score
0.8035
[[1607    0]
 [ 393    0]]

classification_report
              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1607
           1       0.00      0.00      0.00       393

    accuracy                           0.80      2000
   macro avg       0.40      0.50      0.45      2000
weighted avg       0.65      0.80      0.72      2000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))